apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-serving-gateway
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-serving-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      dubhe.io/owner: "dubhe"
      dubhe.io/application: "dubhe-backend-serving-gateway"
  template:
    metadata:
      labels:
        dubhe.io/owner: "dubhe"
        dubhe.io/application: "dubhe-backend-serving-gateway"
    spec:
      initContainers:
        - name: backend-init
          image: "{{ .Values.dubhe.registry }}/backend-init:v1"
      containers:
        - name: dubhe-backend-serving-gateway
          image: "{{ .Values.dubhe.registry }}/backend-serving-gateway:v1"
          ports:
            - name: tcp
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8081
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8081
          envFrom:
            - configMapRef:
                name: dubhe
          volumeMounts:
            - name: data
              mountPath: /nfs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dubhe-vol

---
apiVersion: v1
kind: Service
metadata:
  name: backend-serving-gateway
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-serving-gateway"
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: port-8081
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-serving-gateway"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-serving-gateway-console
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-serving-gateway"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: gateway
      nodePort: 30081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-serving-gateway"
  type: NodePort
