apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-terminal
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-terminal"
spec:
  replicas: 1
  selector:
    matchLabels:
      dubhe.io/owner: "dubhe"
      dubhe.io/application: "dubhe-backend-terminal"
  template:
    metadata:
      labels:
        dubhe.io/owner: "dubhe"
        dubhe.io/application: "dubhe-backend-terminal"
    spec:
      initContainers:
        - name: backend-init
          image: "{{ .Values.dubhe.registry }}/backend-init:v1"
      containers:
        - name: dubhe-backend-terminal
          image: "{{ .Values.dubhe.registry }}/backend-terminal:v1"
          ports:
            - name: tcp
              containerPort: 8970
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8970
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8970
          envFrom:
            - configMapRef:
                name: dubhe
          volumeMounts:
            - name: data
              mountPath: /nfs
            - name: "dockersock"
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dubhe-vol
        - name: "dockersock"
          hostPath:
            path: "/var/run/docker.sock"
---
apiVersion: v1
kind: Service
metadata:
  name: dubhe-terminal
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-terminal"
spec:
  ports:
    - port: 8970
      targetPort: 8970
      name: port-8970
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-terminal"
