apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-k8s"
spec:
  replicas: 1
  selector:
    matchLabels:
      dubhe.io/owner: "dubhe"
      dubhe.io/application: "dubhe-backend-k8s"
  template:
    metadata:
      labels:
        dubhe.io/owner: "dubhe"
        dubhe.io/application: "dubhe-backend-k8s"
    spec:
      initContainers:
        - name: backend-init
          image: "{{ .Values.dubhe.registry }}/backend-init:v1"
      containers:
        - name: dubhe-backend-k8s
          image: "{{ .Values.dubhe.registry }}/backend-k8s:v1"
          ports:
            - name: tcp
              containerPort: 8960
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8960
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8960
          envFrom:
            - configMapRef:
                name: dubhe
          volumeMounts:
            - name: data
              mountPath: /nfs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dubhe-vol

---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-k8s"
spec:
  ports:
    - port: 8960
      targetPort: 8960
      name: port-8960
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-k8s"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-console
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-k8s"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: k8s
      nodePort: 30960
      port: 8960
      protocol: TCP
      targetPort: 8960
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-k8s"
  type: NodePort
