# Default values for tianshu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mysql:
  enable: true
  image: nacos/nacos-mysql:5.7
  port: 3306
  username: "root"
  password: "root"
  database: "nacos_dev"
  storage:
    classname: "nfs-client"
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "0.5"
  #     memory: "512Mi"

redis:
  enable: true
  image: redis:6.2.6-alpine
  password: "Tianshu@123"
  storage:
    classname: "nfs-client"
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "0.5"
  #     memory: "512Mi"

minio:
  enable: true
  image: minio/minio:RELEASE.2020-04-28T23-56-56Z
  accesskey: "admin"
  secretkey: "abcdefg123456"
  storage:
    classname: "nfs-client"
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "0.5"
  #     memory: "512Mi"


dubhe:
  environment: "prod"
  nacos:
    mysql:
      host: xxx.xxx.xxx.xxx
      port: 3306
      dbname: "nacos_dev"
      user: "root"
      password: "root"
#   # harbor
#   harbor:
#     host: "172.16.117.11:5000"
#     username: "admin"
#     password: "Harbor12345"
#   # grafana
#   grafana:
#     host: grafana
#     port: 3000
#   # prometheus
#   prometheus:
#     host: prometheus
#     port: 9090
#   # elasticsearch
#   elasticsearch:
#     host: elasticsearch
#     port: 9200
#   mysql:
#     host: "mysql"
#     dbname: "dubhe-prod"
#     username: "root"
#     password: "root"

#   # Nacos config


#   # Minio config
#   minio:
#     server: "minio.dubhe-system.svc.cluster.local"
#     port: "9000"
#     accesskey: "admin"
#     secretkey: "abcdefg123456"

#   # Redis config


# infra:
#   redis:
#     server: "redis.dubhe-system.svc.cluster.local"
#     password: "Tianshu@123"

# monitoring:
#   exporter:
#     image: prom/node-exporter:v1.7.0
#   grafana:
#     image: grafana/grafana:6.6.0
#   prometheus:
#     image: prom/prometheus:v2.7.1

# elk:
#   fluent: 
#     image: fluent/fluent-bit:2.2.0
#   kibana:
#     image: 
#   elasticsearch:
#     image: prom/prometheus:v2.7.1

# backend:
#   terminal:
#     host: "172.16.117.11"
# # If defined, web service will visit node ip instead of services defined in k8s.
# #假如您的服务器在公网,请把下面的ip换成公网的IP,如果只有内网IP即填写内网IP
# web.proxy.host: "172.16.117.11"
# # # Dubhe code to compile
# # code.repo: "https://gitee.com/zhijiangtianshu/Dubhe.git"
# # code.branch: "master"
# # Environment config

# # Mysql config


# # Backend config
# backend.server: "backend.dubhe-system.svc.cluster.local"
# backend.password: "123456"
# backend.k8s.server: "backend-k8s.dubhe-system.svc.cluster.local"
# backend.gateway.server: "backend-gateway.dubhe-system.svc.cluster.local"
# backend.visual.server: "backend-visual.dubhe-system.svc.cluster.local"
# backend.model-measure.server: "backend-model-measure.dubhe-system.svc.cluster.local"
# backend.model-convert.server: "backend-model-converter.dubhe-system.svc.cluster.local"
# backend.data.server: "backend-data.dubhe-system.svc.cluster.local"
# backend.data.dcm.server: "backend-data-dcm.dubhe-system.svc.cluster.local"
# backend.dcm4chee.server: "backend-dcm4chee.dubhe-system.svc.cluster.local"
# web.server: "web.dubhe-system.svc.cluster.local"
# grafana.server: "172.16.117.11:3000"
# # All image can be configured and redeploy.
# # Image can be rebuild by "./dubhectl build-image", please refer to "./dubhectl help"
# image.imgprocess.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/imgprocess:v1"
# image.ofrecord.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/ofrecord:v1"
# image.videosample.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/videosample:v1"
# image.backend: "registry.cn-hangzhou.aliyuncs.com/enlin/dubhe-java:v1"
# image.backend-init: "172.16.117.11:5000/enlin/backend-init:v1"
# image.backend-visual: "registry.cn-hangzhou.aliyuncs.com/enlin/visual-server:v1"
# image.converter: "registry.cn-hangzhou.aliyuncs.com/enlin/model-converter:v1"
# image.measuring: "registry.cn-hangzhou.aliyuncs.com/enlin/model-measuring:v1"
# image.optimize: "registry.cn-hangzhou.aliyuncs.com/enlin/oneflow-gpu:base"
# image.tadl: "registry.cn-hangzhou.aliyuncs.com/enlin/automl-nas-pytorch17:v1"
# image.minio: "minio/minio:RELEASE.2020-04-28T23-56-56Z"
# image.minio-init: "172.16.117.11:5000/enlin/minio-init:v1"
# image.mysql: "nacos/nacos-mysql:5.7"
# image.mysql-init: "172.16.117.11:5000/enlin/mysql-init:v1"
# image.nacos: "nacos/nacos-server:2.0.3"
# image.nacos-init: "172.16.117.11:5000/enlin/nacos-init:v1"
# image.redis: "redis:5.0.7"
# image.storage-init: "registry.cn-hangzhou.aliyuncs.com/enlin/storage-init:v1"
# # You need build web images separatel. Use command "./dubhectl build-image web"
# image.web: "172.16.117.11:5000/enlin/web:v1"