apiVersion: v1
kind: ConfigMap
metadata:
  name: dubhe
data:
  # Harbor
  HARBOR_HOST: {{ .Values.harbor.host }}
  HARBOR_USERNAME: {{ .Values.harbor.username }}
  HARBOR_PASSWORD: {{ .Values.harbor.password }}

  GRAFANA_HOST: {{ .Values.grafana.host }}
  GRAFANA_PORT: {{ .Values.grafana.port }}

  PROMETHEUS_HOST: {{ .Values.prometheus.host }}
  PROMETHEUS_PORT: {{ .Values.prometheus.port }}

  ELASTICSEARCH_HOST: {{ .Values.elasticsearch.host }}
  ELASTICSEARCH_PORT: {{ .Values.elasticsearch.port }}

  MYSQL_HOST: {{ .Values.mysql.host }}
  MYSQL_PORT: {{ .Values.mysql.port }}
  MYSQL_USERNAME: {{ .Values.mysql.username }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}

  NACOS_HOST: {{ .Values.nacos.host }}
  NACOS_PORT: {{ .Values.nacos.port }}
  NACOS_DB_NAME: {{ .Values.nacos.db.name }}
  NACOS_DB_USERNAME: {{ .Values.nacos.db.username }}
  NACOS_DB_PASSWORD: {{ .Values.nacos.db.password }}

  MINIO_HOST: {{ .Values.minio.host }}
  MINIO_PORT: {{ .Values.minio.port }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accesskey }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretkey }}

  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port }}
  REDIS_PASSWORD: {{ .Values.redis.password }}

  backend.terminal.host: "172.16.117.11"

  web.proxy.host: "172.16.117.11"
  # Dubhe code to compile


  # Environment config
  dubhe.environment: "dubhe-prod"
  # Mysql config
  # Nacos config

  # Minio config

  # Redis config

  # Backend config
  backend.server: "backend.dubhe-system.svc.cluster.local"
  backend.password: "123456"
  backend.k8s.server: "backend-k8s.dubhe-system.svc.cluster.local"
  backend.gateway.server: "backend-gateway.dubhe-system.svc.cluster.local"
  backend.visual.server: "backend-visual.dubhe-system.svc.cluster.local"
  backend.model-measure.server: "backend-model-measure.dubhe-system.svc.cluster.local"
  backend.model-convert.server: "backend-model-converter.dubhe-system.svc.cluster.local"
  backend.data.server: "backend-data.dubhe-system.svc.cluster.local"
  backend.data.dcm.server: "backend-data-dcm.dubhe-system.svc.cluster.local"
  backend.dcm4chee.server: "backend-dcm4chee.dubhe-system.svc.cluster.local"
  web.server: "web.dubhe-system.svc.cluster.local"
  
  # All image can be configured and redeploy.
  # Image can be rebuild by "./dubhectl build-image", please refer to "./dubhectl help"
  image.imgprocess.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/imgprocess:v1"
  image.ofrecord.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/ofrecord:v1"
  image.videosample.algorithm: "registry.cn-hangzhou.aliyuncs.com/enlin/videosample:v1"
  image.backend: "registry.cn-hangzhou.aliyuncs.com/enlin/dubhe-java:v1"
  image.backend-init: "172.16.117.11:5000/enlin/backend-init:v1"
  image.backend-visual: "registry.cn-hangzhou.aliyuncs.com/enlin/visual-server:v1"
  image.converter: "registry.cn-hangzhou.aliyuncs.com/enlin/model-converter:v1"
  image.measuring: "registry.cn-hangzhou.aliyuncs.com/enlin/model-measuring:v1"
  image.optimize: "registry.cn-hangzhou.aliyuncs.com/enlin/oneflow-gpu:base"
  image.tadl: "registry.cn-hangzhou.aliyuncs.com/enlin/automl-nas-pytorch17:v1"
  image.minio: "minio/minio:RELEASE.2020-04-28T23-56-56Z"
  image.minio-init: "172.16.117.11:5000/enlin/minio-init:v1"
  image.mysql: "nacos/nacos-mysql:5.7"
  image.mysql-init: "172.16.117.11:5000/enlin/mysql-init:v1"
  image.nacos: "nacos/nacos-server:2.0.3"
  image.nacos-init: "172.16.117.11:5000/enlin/nacos-init:v1"
  image.redis: "redis:5.0.7"
  image.storage-init: "registry.cn-hangzhou.aliyuncs.com/enlin/storage-init:v1"
  # You need build web images separatel. Use command "./dubhectl build-image web"
  image.web: "172.16.117.11:5000/enlin/web:v1"