apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      dubhe.io/owner: "dubhe"
      dubhe.io/application: "dubhe-backend-gateway"
  template:
    metadata:
      labels:
        dubhe.io/owner: "dubhe"
        dubhe.io/application: "dubhe-backend-gateway"
    spec:
      initContainers:
        - name: backend-init
          image: "{{ .Values.dubhe.registry }}/backend-init:v1"
          volumeMounts:
            - name: data
              mountPath: /nfs
      containers:
        - name: dubhe-backend-gateway
          image: "{{ .Values.dubhe.registry }}/gateway:v1"
          ports:
            - name: tcp
              containerPort: 8800
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8800
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8800
          envFrom:
            - configMapRef:
                name: dubhe
          volumeMounts:
            - name: data
              mountPath: /nfs
      volumes:
        - name: data
          # nfs:
          #   server: 
          #   path: /data/dubhe/dubhe-storage
          hostPath:
            path: /data/dubhe/dubhe-storage

---
apiVersion: v1
kind: Service
metadata:
  name: backend-gateway
  labels:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-gateway"
spec:
  ports:
    - port: 8800
      targetPort: 8800
      name: port-8800
  selector:
    dubhe.io/owner: "dubhe"
    dubhe.io/application: "dubhe-backend-gateway"
